name = "visitor-message-worker"
main = "src/index.js"
compatibility_date = "2026-03-03"
workers_dev = true
preview_urls = false

[vars]
ALLOWED_ORIGIN = "https://wenyuedai.github.io"
NOTION_TITLE_PROPERTY = "Name"

[[kv_namespaces]]
binding = "VISIT_STATS"
id = "dcb3586a8a0e43c8a8abc482b3679d7c"
preview_id = "dcb3586a8a0e43c8a8abc482b3679d7c"
